# Train parameters
model: None
model-pretrained: False
tokenizer: gpt2
tokenizer-pretrained: True
hf-model-config: distilgpt2
hf-model-config-pretrained: distilgpt2
optimizer: Adas
scheduler: linear
batch-size: 1
batch-size-eval: 1
max-src-length: 512
max-tgt-length: 512
max-epochs: 25
num-trials: 1
loss: cross_entropy
clip-grad: 1.0
optimizer-kwargs:
  lr: ['loguniform', 0.03, 0.05]
  weight_decay: ['loguniform', 0.00001, 0.01]
  linear: True
  beta: 0.95
  step_size: 25
  momentum: ['choice', 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

scheduler-kwargs:
  num_warmup_steps: 500
mask: False
pad-to-max-length: True
ray-tune: True
ray-tune-samples: 50

# Data Parameters
data-name: wikitext
data-config: wikitext-2-raw-v1
train-src: /home/mat/archive/datasets/smcalflow/prepared-context2/train.json
val-src: /home/mat/archive/datasets/smcalflow/prepared-context2/valid.json
vocab: /home/mat/archive/datasets/smcalflow/prepared-context2/vocab.txt
task: clm
overwrite-cache: False
num-workers: 4
max-train-samples: 1000
max-val-samples: 1000
# tokenizer-files:

checkpoint: /home/mat/archive/playground/_test-checkpoint
cache-dir: /home/mat/archive/playground/_test-cache
output: /home/mat/archive/playground/_test-output
save-freq: 1
